plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/pe_mbp/Peggy/pe2026/PESU_WEB"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]